### ISSUE TITLE
Feature Request: Existing User Management

### ISSUE THREAD

**Issue by tgelite** [dczysz/caddy-auth-user-manager#1]
This looks great, and we can deploy this under caddy and protect with caddy_auth_portal / caddy_auth_jwt plugin configuration. I'll share config example once we set up and test. 

A few improvement requests: 

1) For the list of existing users do not display superadmin (it should never be acted on by users or managers).  Not sure if other users want to see this either.
2) For non superuser accounts, provide disable/remove functionality for a user
3) Update the readme.md to indicate config.js needs to be updated to point to where the user DB files are.
4) Can you make this project MIT license plz.

**Comment by dczysz** [comment]
>3. Update the readme.md to indicate config.js needs to be updated to point to where the user DB files are.

Good idea.  I'll probably also do something like this so the paths could be changed either by using environment variables _or_ editing config.js.

```js
exports.USER_DB_PATH = process.env.USER_DB_PATH || './test-data/user_db.json';
```

The others are straightforward and good ideas, I'll get them done 👍

**Comment by dczysz** [comment]
@tgelite how's this look?

**Comment by tgelite** [comment]
Looks really good. Great work.  Please merge and we'll pull into main project.  I've indicated how we are laying it down in the caddyfile's UI section, and will add the necessary "route" to the runtime instance and JWT authorization protection for that issue#27 from elite-pi update for Caddyfile.
